# Site settings
title: ZXZ Blog
SEOTitle: 张鑫泽的博客 | ZXZ Blog
header-img: img/post-bg-universe.jpg
email: 1411187672@qq.com
description: "落花，流水，我的时间和代码...^.^"
keyword: "张鑫泽,昝晓婷,前端,梦三国,王者荣耀,篮球,游泳,跑步,C#,HTML,CSS,JS,JQuery,Bootstrap,vue,AJAX,JSON,Java"
url: "https://github.com/BeeMan-zxz"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/BeeMan-zxz/BeeMan-zxz.github.io.git"


# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     u/7084253381
zhihu_username:     u/e16882040a69   
github_username:    BeeMan-zxz
# twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: Diaomin923

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 1807d3fe98c6a45d38d0   #生成的clientID
  clientSecret: 695d2f3f679f361308ed78291534afc08b180246  #同上
  repo: BeeMan-zxz.github.io    #仓库名称
  owner: BeeMan-zxz    #github用户名
  admin: BeeMan-zxz
  id: window.location.pathname
  distractionFreeMode: true #是否启用类似FB的阴影遮罩





# Disqus settings
disqus_username: zxz

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "吃饭,睡觉,逛街,健身,敲代码,简单的生活简单的幸福..."
sidebar-avatar: /img/1.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
         title: "前端-颜色库",
         href: "https://flatuicolors.com/"
     },{
        title: "W3c",
        href: "https://www.w3cschool.cn/"
    },{
        title: "js宝藏",
        href: "http://fgm.cc/learn/"
    },{
        title: "hexo框架",
        href: "https://hexo.io/themes/"
    },{
        title: "酷炫网页",
        href: "https://tympanus.net/codrops/"
    },{
        title: "17素材网",
        href: "http://www.17sucai.com/"
    },{
        title: "阮一峰js博文",
        href: "http://www.ruanyifeng.com/blog/javascript/"
    },{
         title: "MDN web docs",
         href: "https://developer.mozilla.org/zh-CN/"
    },{
        # title: "DHong Say",
        # href: "http://dhong.co"
    },{
        # title: "尹峰以为",
        # href: "http://ingf.github.io/"
    },{
        # title: "解旻的博客",
        # href: "http://xieminis.me/"
    }
]
